# Generated by Django 5.1.6 on 2025-04-04 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('queue_site', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='theme',
            field=models.CharField(choices=[('white', 'Белая'), ('blue', 'Синяя'), ('purple', 'Фиолетовая'), ('orange', 'Оранжевая')], default='white', max_length=10),
        ),
    ]
