# Generated by Django 5.1.6 on 2025-04-14 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('queue_site', '0002_user_theme'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='telegram_id',
            field=models.CharField(blank=True, help_text='Telegram ID пользователя для привязки аккаунта.', max_length=32, null=True, unique=True),
        ),
    ]
