# Generated by Django 5.1.6 on 2025-04-14 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('queue_site', '0003_user_telegram_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(help_text='Ваш email (обязательное поле).', max_length=254),
        ),
    ]
