# Generated by Django 5.1.6 on 2025-04-14 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('queue_site', '0004_alter_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(help_text='Ваш email (обязательное поле).', max_length=254, unique=True),
        ),
    ]
